PRAGMA foreign_keys = ON;

CREATE TABLE conf (
    id INTEGER NOT NULL PRIMARY KEY, -- for SQLite
    -- id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- for PostgreSQL

    -- Model spec (including token set specification).
    spec TEXT NOT NULL,
    -- Number of weights in the model.
    weights INTEGER NOT NULL,

    -- One of 'fp32', 'fp16', 'bf16'
    precision TEXT NOT NULL DEFAULT 'fp32',

    -- Learning rate.
    lr REAL NOT NULL,

    decay REAL NOT NULL DEFAULT 1,

    -- Use a cosine LR schedule that decays to 0 over `steps` (no
    -- warmup, no floor). Stored as 0/1; mutually exclusive with
    -- exponential `decay`: when cosine=1, decay must be 1.
    cosine INTEGER NOT NULL DEFAULT 0,

    length INTEGER NOT NULL,
    batch INTEGER NOT NULL,
    steps INTEGER NOT NULL,

    -- Number of intermediate layers in the spec (everything between
    -- the input and the output dense, counting suffix/norm/skip).
    -- Populated on insert; NULL for rows from before this column was
    -- added (run the db-backfill-num-layers CLI to fix those).
    num_layers INTEGER,

    -- When 1, the search picks this conf preferentially over its other
    -- strategies until it has accumulated `PICK_ME_MIN_RUNS` total runs.
    -- Used to inject specific candidates we want to evaluate quickly
    -- (e.g. the strip-leading-norm migration that creates valid
    -- variants of invalid `<input>|norm-X.Y.Z-...` confs). The min-runs
    -- gate is enforced at SELECT time, not by clearing the flag, so the
    -- writer doesn't need to participate.
    pick_me INTEGER NOT NULL DEFAULT 0,

    -- Scores based on the runs.
    median_score REAL,

    UNIQUE (spec, precision, lr, decay, cosine, length, batch, steps)
);

CREATE INDEX conf_spec ON conf(spec);
CREATE INDEX conf_median_score ON conf(median_score);

CREATE TABLE run (
    id INTEGER NOT NULL PRIMARY KEY, -- for SQLite
    -- id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- for PostgreSQL

    conf_id INTEGER NOT NULL,

    -- The name of the machine on which the run was executed.
    system TEXT NOT NULL,

    -- Time in seconds from the end of the first optimization step till the
    -- end of the optimization. Stored as 0 if the run diverged before a
    -- usable time could be measured (the column is NOT NULL, so 0 is the
    -- in-band sentinel for "no signal"). Read paths in db/reader.py should
    -- translate 0 back to None so downstream consumers don't mistake it
    -- for an instant-fast run.
    train_time REAL NOT NULL,

    -- Timestamp in ISO8601 when the run occured.
    timestamp TIMESTAMP,

    test_sample_len INTEGER,
    test_batch INTEGER,

    -- Final loss per byte on the eval sample.
    loss REAL NOT NULL,

    -- A 1D array of training losses after each step, encoded as
    -- ndarray(dtype=np.float32) and converted to bytes by ndarray.tobytes().
    -- Can be converted back to an array by np.frombuffer().
    step_loss BLOB,  -- for SQLite
    -- step_loss BYTEA,  -- for PostgreSQL

    -- Loss model version.
    loss_model_v INTEGER,
    -- Parameters of loss model as ndarray(dtype=np.float32).
    loss_model BLOB,  -- for SQLite
    -- loss_model BYTEA,  -- for PostgreSQL

    -- If non-empty, this contains the filename of the weights checkpoint.
    checkpoint TEXT,

    -- Which search strategy picked the conf that produced this run.
    -- One of: 'predicted_2nd_neighbor', 'predicted_3rd_neighbor',
    -- 'time_budget', 'neighbor', 'default'. May also include
    -- 'hill_climb' on older runs (the strategy was retired).
    -- NULL for runs added before the column existed or for
    -- out-of-band inserts (bulk imports, tests).
    strategy TEXT,

    -- 1 if this run changed the conf winning at (system, train_time,
    -- num_weights); 0 if not; NULL if the check was skipped (e.g. a
    -- bulk import that didn't pass through the server).
    changed_winner INTEGER,

    FOREIGN KEY (conf_id) REFERENCES conf(id) ON DELETE CASCADE,
    UNIQUE (conf_id, system, timestamp)
);

CREATE INDEX run_conf_id ON run(conf_id);

-- Per-conf, per-system training-time estimate. Either the median of
-- observed runs (source='median') or a prediction from the timing
-- model (source='predicted'). Precision is determined by conf.precision
-- so it's not stored here.
CREATE TABLE conf_time_estimate (
    conf_id INTEGER NOT NULL,
    system TEXT NOT NULL,
    time_s REAL NOT NULL,
    source TEXT NOT NULL CHECK (source IN ('median', 'predicted')),
    UNIQUE (conf_id, system),
    FOREIGN KEY (conf_id) REFERENCES conf(id) ON DELETE CASCADE
);

CREATE INDEX conf_time_estimate_conf_id ON conf_time_estimate(conf_id);
-- Lets `confs_under_time` and the writer's TOP_CONF_AT query filter
-- cte by (system, time_s<=t) without scanning the 3M-row table.
CREATE INDEX conf_time_estimate_system_time
    ON conf_time_estimate(system, time_s);
-- Lets `top_confs_global` look up min(time_s) and the winning system
-- per conf without a temp B-tree sort.
CREATE INDEX conf_time_estimate_conf_time
    ON conf_time_estimate(conf_id, time_s);

-- Serialized trained models (pickled). `name` is a short key like
-- 'timing' or 'loss'. Saved by ModelTrainingThread after each refit
-- so restarts don't have to redo minutes of training.
CREATE TABLE model (
    name TEXT NOT NULL PRIMARY KEY,
    data BLOB NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
