"""Tests for the training-time prediction model."""

import numpy as np
import pytest

from texmo.configuration import Configuration
from texmo.model import build_model_def
from texmo.precision import Precision
from texmo.predict.timing import TrainTimingModel, _fit, featurize, predict_time
from texmo.run import Run


def _conf(
    spec: str,
    lr: float = 0.01,
    length: int = 64,
    batch: int = 16,
    steps: int = 100,
    decay: float = 1.0,
    precision: Precision = Precision.FP32,
) -> Configuration:
    return Configuration(
        build_model_def(spec, precision=precision),
        lr=lr,
        length=length,
        batch=batch,
        steps=steps,
        decay=decay,
    )


def test_featurize_types():
    conf = _conf("bits.1+bp|dense.8.gelu", batch=16, length=32)
    comps = featurize(conf)
    assert len(comps) == 3
    assert comps[0].type_id == "bits.1+bp"
    assert comps[1].type_id == "dense.gelu"
    assert comps[2].type_id == "output"


def test_featurize_feature_sizes():
    """Different types have different feature vector lengths."""
    conf = _conf("bits.1+bp|dense.8.gelu-suffix.2-skip.1.add-norm", batch=4, length=10)
    comps = featurize(conf)
    types = {c.type_id: c.features.shape[0] for c in comps}
    assert types["bits.1+bp"] == 3  # input
    assert types["dense.gelu"] == 12  # dense_matmul
    assert types["suffix"] == 10  # plain + suffix_length
    assert types["skip.add"] == 4  # minimal
    assert types["norm"] == 9  # plain
    assert types["output"] == 12  # dense_matmul


def test_featurize_base_values():
    """Base features: [1, L, B*L, IS, IS*L, IS*B*L, OS, OS*L, OS*B*L]."""
    conf = _conf("bits.1+bp|dense.8.gelu", batch=4, length=10)
    comps = featurize(conf)
    # Dense: IS=4 (bits.1+bp.size), OS=8, B=4, L=10
    dense = comps[1]
    bl = 40
    expected_base = [1, 10, bl, 4, 40, 160, 8, 80, 320]
    expected_matmul = [32, 320, 4 * 8 * bl]
    np.testing.assert_array_equal(dense.features, expected_base + expected_matmul)


def test_featurize_suffix_length_feature():
    conf = _conf("bits.1+bp|suffix.4", batch=2, length=8)
    comps = featurize(conf)
    suffix = comps[1]
    assert suffix.type_id == "suffix"
    # Last feature is the suffix_length.
    assert suffix.features[-1] == 4


def test_featurize_skip_features():
    conf = _conf("bits.1+bp|skip.1.cat-dense.4.tanh", batch=2, length=8)
    comps = featurize(conf)
    skip = comps[1]
    assert skip.type_id == "skip.cat"
    # [1, IS=4, IS*L=32, IS*B*L=64]
    np.testing.assert_array_equal(skip.features, [1, 4, 32, 64])


def test_predict_with_known_weights():
    """If only the constant feature has nonzero weight, prediction = constant
    × number of components (all sized by their feature count)."""
    conf = _conf("bits.1+bp|dense.8.gelu", batch=4, length=10)
    comps = featurize(conf)
    c = 0.001
    log_c = np.log(c)
    weights = {}
    for comp in comps:
        theta = np.full(comp.features.shape[0], -50.0)  # exp(-50) ≈ 0
        theta[0] = log_c  # constant feature
        weights[comp.type_id] = theta
    pred = predict_time(weights, comps)
    assert pytest.approx(pred, rel=1e-5) == c * len(comps)


def test_predict_missing_weights_gives_zero():
    """Components with no fitted weights contribute 0 (graceful for
    types absent from training data)."""
    conf = _conf("bits.1+bp|dense.8.gelu", batch=4, length=10)
    comps = featurize(conf)
    assert predict_time({}, comps) == 0.0


def test_fit_synthetic_linear():
    """Fit on synthetic data generated by a known linear model."""
    rng = np.random.default_rng(0)

    # Ground-truth: each type has a single dominant feature.
    # Feature indices per type depend on the feature layout — we just
    # pick one feature per type and set a coefficient on it.
    truth = {
        "bits.1+bp": (0, 0.001),  # constant
        "dense.gelu": (11, 1e-9),  # IS*OS*B*L (last matmul feature)
        "output": (11, 2e-9),  # IS*OS*B*L
    }

    samples = []
    for _ in range(100):
        batch = int(rng.choice([4, 8, 16, 32, 64]))
        length = int(rng.choice([16, 32, 64, 128]))
        conf = _conf("bits.1+bp|dense.8.gelu", batch=batch, length=length)
        comps = featurize(conf)
        t = sum(
            coef * comp.features[idx]
            for comp in comps
            for (idx, coef) in [truth.get(comp.type_id, (0, 0))]
        )
        samples.append((comps, t))

    weights, loss = _fit(samples, steps=2000)
    assert loss < 0.05, f"loss too high: {loss}"

    for comps, actual in samples[:10]:
        pred = predict_time(weights, comps)
        assert pytest.approx(pred, rel=0.3) == actual


def _fake_run(system: str, train_time: float) -> Run:
    return Run(train_time=train_time, system=system)


def test_model_fit_and_predict():
    """End-to-end: generate synthetic per-step times, fit, predict."""
    rng = np.random.default_rng(1)
    samples = []
    for _ in range(80):
        length = int(rng.choice([32, 64, 128]))
        batch = int(rng.choice([8, 16, 32]))
        spec = "bits.1+bp|dense.8.gelu"
        conf = _conf(spec, batch=batch, length=length, steps=100)
        comps = featurize(conf)
        # Use a matmul feature from the dense layer as the "signal".
        # Dense layer is comps[1]; feature 11 is IS*OS*B*L.
        signal = comps[1].features[11]
        per_step = 0.02 + 1e-7 * signal
        run = _fake_run("testbench", per_step * (conf.steps - 1))
        samples.append((conf, run))

    model = TrainTimingModel()
    model.fit(samples)
    assert ("testbench", Precision.FP32) in model.keys()

    conf = _conf("bits.1+bp|dense.8.gelu", batch=24, length=48)
    pred = model.predict("testbench", conf)
    comps = featurize(conf)
    signal = comps[1].features[11]
    expected = 0.02 + 1e-7 * signal
    assert pytest.approx(pred, rel=0.3) == expected


def test_model_unknown_system_returns_none():
    model = TrainTimingModel()
    conf = _conf("bits.1+bp|dense.8.gelu")
    assert model.predict("nope", conf) is None
    assert model.predict_batch("nope", [conf]) is None


def test_model_skips_diverged_runs():
    rng = np.random.default_rng(2)
    samples = []
    for _ in range(80):
        batch = int(rng.choice([4, 8, 16]))
        length = int(rng.choice([32, 64]))
        conf = _conf("bits.1+bp|dense.8.gelu", batch=batch, length=length)
        if rng.random() < 0.5:
            run = _fake_run("test", None)
        else:
            run = _fake_run("test", 0.05 * (conf.steps - 1))
        samples.append((conf, run))

    model = TrainTimingModel()
    model.fit(samples)
    assert ("test", Precision.FP32) in model.keys()
