PRAGMA foreign_keys = ON;

CREATE TABLE conf (
    id INTEGER NOT NULL PRIMARY KEY, -- for SQLite
    -- id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- for PostgreSQL

    -- Model spec (including token set specification).
    spec TEXT NOT NULL,
    -- Number of weights in the model.
    weights INTEGER NOT NULL,

    -- One of 'fp32', 'fp16', 'bf16'
    precision TEXT NOT NULL DEFAULT 'fp32',

    -- Learning rate.
    lr REAL NOT NULL,

    decay REAL NOT NULL DEFAULT 1,

    length INTEGER NOT NULL,
    batch INTEGER NOT NULL,
    steps INTEGER NOT NULL,

    -- Scores based on the runs.
    median_score REAL,

    UNIQUE (spec, precision, lr, decay, length, batch, steps)
);

CREATE INDEX conf_spec ON conf(spec);
CREATE INDEX conf_median_score ON conf(median_score);

CREATE TABLE run (
    id INTEGER NOT NULL PRIMARY KEY, -- for SQLite
    -- id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- for PostgreSQL

    conf_id INTEGER NOT NULL,

    -- The name of the machine on which the run was executed.
    system TEXT NOT NULL,

    -- Time in seconds from the end of the first optimization step till the
    -- end of the optimization.
    train_time REAL NOT NULL,

    -- Timestamp in ISO8601 when the run occured.
    timestamp TIMESTAMP,

    test_sample_len INTEGER,
    test_batch INTEGER,

    -- Final loss per byte on the eval sample.
    loss REAL NOT NULL,

    -- A 1D array of training losses after each step, encoded as
    -- ndarray(dtype=np.float32) and converted to bytes by ndarray.tobytes().
    -- Can be converted back to an array by np.frombuffer().
    step_loss BLOB,  -- for SQLite
    -- step_loss BYTEA,  -- for PostgreSQL

    -- Loss model version.
    loss_model_v INTEGER,
    -- Parameters of loss model as ndarray(dtype=np.float32).
    loss_model BLOB,  -- for SQLite
    -- loss_model BYTEA,  -- for PostgreSQL

    -- If non-empty, this contains the filename of the weights checkpoint.
    checkpoint TEXT,

    FOREIGN KEY (conf_id) REFERENCES conf(id) ON DELETE CASCADE,
    UNIQUE (conf_id, system, timestamp)
);

CREATE INDEX run_conf_id ON run(conf_id);

-- Per-conf, per-system training-time estimate. Either the median of
-- observed runs (source='median') or a prediction from the timing
-- model (source='predicted'). Precision is determined by conf.precision
-- so it's not stored here.
CREATE TABLE conf_time_estimate (
    conf_id INTEGER NOT NULL,
    system TEXT NOT NULL,
    time_s REAL NOT NULL,
    source TEXT NOT NULL CHECK (source IN ('median', 'predicted')),
    UNIQUE (conf_id, system),
    FOREIGN KEY (conf_id) REFERENCES conf(id) ON DELETE CASCADE
);

CREATE INDEX conf_time_estimate_conf_id ON conf_time_estimate(conf_id);

-- Serialized trained models (pickled). `name` is a short key like
-- 'timing' or 'loss'. Saved by ModelTrainingThread after each refit
-- so restarts don't have to redo minutes of training.
CREATE TABLE model (
    name TEXT NOT NULL PRIMARY KEY,
    data BLOB NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
