CREATE TABLE conf (
    id INTEGER NOT NULL PRIMARY KEY, -- for SQLite
    -- id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- for PostgreSQL

    -- Model3 spec (including token set specification).
    spec TEXT NOT NULL,
    -- Number of weights in the model.
    weights INTEGER NOT NULL,

    -- Learning rate.
    lr REAL NOT NULL,
    length INTEGER NOT NULL,
    batch INTEGER NOT NULL,
    steps INTEGER NOT NULL,

    UNIQUE (spec, lr, length, batch, steps)
);

CREATE INDEX conf_spec ON conf(spec);

CREATE TABLE run (
    id INTEGER NOT NULL PRIMARY KEY, -- for SQLite
    -- id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- for PostgreSQL

    conf_id INTEGER NOT NULL,

    -- The name of the machine on which the run was executed.
    system TEXT NOT NULL,

    -- Time in seconds from the end of the first optimization step till the
    -- end of the optimization.
    train_time REAL NOT NULL,

    -- Timestamp in ISO8601 when the run occured.
    timestamp TIMESTAMP,

    test_sample_len INTEGER,
    test_batch INTEGER,

    -- Final loss per byte on the eval sample.
    loss REAL NOT NULL,

    -- A 1D array of training losses after each step, encoded as
    -- ndarray(dtype=np.float32) and converted to bytes by ndarray.tobytes().
    -- Can be converted back to an array by np.frombuffer().
    step_loss BLOB,  -- for SQLite
    -- step_loss BYTEA,  -- for PostgreSQL

    -- Loss model version.
    loss_model_v INTEGER,
    -- Parameters of loss model as ndarray(dtype=np.float32).
    loss_model BLOB,  -- for SQLite
    -- loss_model BYTEA,  -- for PostgreSQL

    -- If non-empty, this contains the filename of the weights checkpoint.
    checkpoint TEXT,

    FOREIGN KEY (conf_id) REFERENCES conf(id),
    UNIQUE (conf_id, system, timestamp)
);

CREATE INDEX run_conf_id ON run(conf_id);
